In [1]:
import requests
import json
import pandas as pd
import csv
import os

In [2]:
beers_data= "beers-cleaned.csv"

beers_df = pd.read_csv(beers_data, encoding = "ISO-8859-1", engine='python')
beers_df.head()

,id,brewery_id,name,cat_id,style_id,abv,ibu,srm,upc,descript,...,Unnamed: 205,Unnamed: 206,Unnamed: 207,Unnamed: 208,Unnamed: 209,Unnamed: 210,Unnamed: 211,Unnamed: 212,Unnamed: 213,Unnamed: 214
0,2,264,Grimbergen Blonde,-1,-1,6.7,10.0,0.0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,779,Widdershins Barleywine,-1,-1,9.1,10.0,0.0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4,287,Lucifer,-1,-1,8.5,10.0,0.0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5,1056,Bitter,-1,-1,4.0,10.0,0.0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,7,1099,Winter Welcome 2007-2008,-1,-1,6.0,10.0,0.0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
beer_df = beers_df.loc[:, ["brewery_id", "name", "style_id", "abv", "ibu"]]
beer_df.head()

   brewery_id                      name  style_id  abv   ibu
0         264         Grimbergen Blonde        -1  6.7  10.0
1         779    Widdershins Barleywine        -1  9.1  10.0
2         287                   Lucifer        -1  8.5  10.0
3        1056                    Bitter        -1  4.0  10.0
4        1099  Winter Welcome 2007-2008        -1  6.0  10.0

In [4]:
breweries_data= "breweries.csv"

breweries_df = pd.read_csv(breweries_data, encoding = "ISO-8859-1", engine='python')
breweries_df = breweries_df.rename(columns={'id': "brewery_id", "name": "brewery_name"})
breweries_df.head()

,brewery_id,brewery_name,address1,address2,city,state,code,country,phone,website,filepath,descript,last_mod
0,1,(512) Brewing Company,"407 Radam, F200",NaN,Austin,Texas,78745,United States,512.707.2337,http://512brewing.com/,NaN,(512) Brewing Company is a microbrewery locate...,7/22/2010 20:00
1,2,21st Amendment Brewery Cafe,563 Second Street,NaN,San Francisco,California,94107,United States,1-415-369-0900,http://www.21st-amendment.com/,NaN,The 21st Amendment Brewery offers a variety of...,10/24/2010 13:54
2,8,Abbey Wright Brewing/Valley Inn,204 Valley Street,NaN,Williamsport,Pennsylvania,17702,United States,570.326.3383,http://www.valleyinnonline.com/,NaN,NaN,7/22/2010 20:00
3,9,Aberdeen Brewing,210 Aberdeen Dr.,NaN,Valparaiso,Indiana,NaN,United States,(219) 548-3300,NaN,NaN,NaN,7/22/2010 20:00
4,10,Abita Brewing Company,PO Box 1510,NaN,Abita Springs,Louisiana,70420,United States,800-737-2311,http://www.abita.com/,NaN,"Founded in 1986, the Abita Brewing Company is ...",7/22/2010 20:00

In [5]:
breweries_df.drop(['address2', 'code', 'filepath', 'last_mod'], axis=1, inplace=True)                          
breweries_df.head()

,brewery_id,brewery_name,address1,city,state,country,phone,website,descript
0,1,(512) Brewing Company,"407 Radam, F200",Austin,Texas,United States,512.707.2337,http://512brewing.com/,(512) Brewing Company is a microbrewery locate...
1,2,21st Amendment Brewery Cafe,563 Second Street,San Francisco,California,United States,1-415-369-0900,http://www.21st-amendment.com/,The 21st Amendment Brewery offers a variety of...
2,8,Abbey Wright Brewing/Valley Inn,204 Valley Street,Williamsport,Pennsylvania,United States,570.326.3383,http://www.valleyinnonline.com/,NaN
3,9,Aberdeen Brewing,210 Aberdeen Dr.,Valparaiso,Indiana,United States,(219) 548-3300,NaN,NaN
4,10,Abita Brewing Company,PO Box 1510,Abita Springs,Louisiana,United States,800-737-2311,http://www.abita.com/,"Founded in 1986, the Abita Brewing Company is ..."

In [6]:
beer_df = beer_df.rename(columns={'name': "beer_name"})
beer_df.head()

   brewery_id                 beer_name  style_id  abv   ibu
0         264         Grimbergen Blonde        -1  6.7  10.0
1         779    Widdershins Barleywine        -1  9.1  10.0
2         287                   Lucifer        -1  8.5  10.0
3        1056                    Bitter        -1  4.0  10.0
4        1099  Winter Welcome 2007-2008        -1  6.0  10.0

In [7]:
styles_data= "styles.csv"

styles_df = pd.read_csv(styles_data, encoding = "ISO-8859-1", engine='python')
styles_df.head(2)

,id,cat_id,style_name,Description,ABV_Low,ABV_High,IBU_low,IBU_High,SRM_Low,SRM_High,OG_Low,OG_High,FG_Low,FG_High,Glass Type
0,1,1,Classic English-Style Pale Ale,Classic English pale ales are golden to copper...,4.5,5.5,20,40,5.0,5.0,NaN,NaN,1.008,1.016,Stein
1,2,1,English-Style India Pale Ale,Most traditional interpretations of English-st...,5.0,7.0,35,63,6.0,14.0,NaN,NaN,1.012,1.018,Nonic Pint

In [8]:
styles_df = styles_df.loc[:, ["id","style_name", "Description"]]
styles_df.head(2)

,id,style_name,Description
0,1,Classic English-Style Pale Ale,Classic English pale ales are golden to copper...
1,2,English-Style India Pale Ale,Most traditional interpretations of English-st...

In [9]:
beer_styles = pd.merge(beer_df, styles_df, left_on="style_id", right_on="id")
beer_styles.head()

,brewery_id,beer_name,style_id,abv,ibu,id,style_name,Description
0,264,Grimbergen Blonde,-1,6.7,10.0,-1,Undefined-Ignore,anomaly 5
1,779,Widdershins Barleywine,-1,9.1,10.0,-1,Undefined-Ignore,anomaly 5
2,287,Lucifer,-1,8.5,10.0,-1,Undefined-Ignore,anomaly 5
3,1056,Bitter,-1,4.0,10.0,-1,Undefined-Ignore,anomaly 5
4,1099,Winter Welcome 2007-2008,-1,6.0,10.0,-1,Undefined-Ignore,anomaly 5

In [10]:
brewery_beer = pd.merge(breweries_df, beer_styles, on="brewery_id")
brewery_beer.head(2)

,brewery_id,brewery_name,address1,city,state,country,phone,website,descript,beer_name,style_id,abv,ibu,id,style_name,Description
0,1,(512) Brewing Company,"407 Radam, F200",Austin,Texas,United States,512.707.2337,http://512brewing.com/,(512) Brewing Company is a microbrewery locate...,(512) Pecan Porter,25,6.8,10.0,25,Porter,Porters are great!
1,1,(512) Brewing Company,"407 Radam, F200",Austin,Texas,United States,512.707.2337,http://512brewing.com/,(512) Brewing Company is a microbrewery locate...,(512) Whiskey Barrel Aged Double Pecan Porter,25,8.2,10.0,25,Porter,Porters are great!

In [11]:
geo_data= "breweries_geocode.csv"

geo_df = pd.read_csv(geo_data, encoding = "ISO-8859-1", engine='python')
geo_df.head(2)

   id  brewery_id  latitude  longitude accuracy                 location
0   1           1   30.2234   -97.7697  ROOFTOP  POINT(-97.7697 30.2234)
1   2           2   37.7825  -122.3930  ROOFTOP  POINT(-122.393 37.7825)

In [12]:
beerdf = pd.merge(brewery_beer, geo_df, on="brewery_id")
beerdf.head(2)

,brewery_id,brewery_name,address1,city,state,country,phone,website,descript,beer_name,...,abv,ibu,id_x,style_name,Description,id_y,latitude,longitude,accuracy,location
0,1,(512) Brewing Company,"407 Radam, F200",Austin,Texas,United States,512.707.2337,http://512brewing.com/,(512) Brewing Company is a microbrewery locate...,(512) Pecan Porter,...,6.8,10.0,25,Porter,Porters are great!,1,30.2234,-97.7697,ROOFTOP,POINT(-97.7697 30.2234)
1,1,(512) Brewing Company,"407 Radam, F200",Austin,Texas,United States,512.707.2337,http://512brewing.com/,(512) Brewing Company is a microbrewery locate...,(512) Whiskey Barrel Aged Double Pecan Porter,...,8.2,10.0,25,Porter,Porters are great!,1,30.2234,-97.7697,ROOFTOP,POINT(-97.7697 30.2234)

In [13]:
beerdf = beerdf.loc[:, ["brewery_name","beer_name", "abv", "ibu","style_name", "address1", "city", "state","latitude","longitude","website"]]
beerdf

,brewery_name,beer_name,abv,ibu,style_name,address1,city,state,latitude,longitude,website
0,(512) Brewing Company,(512) Pecan Porter,6.8,10.0,Porter,"407 Radam, F200",Austin,Texas,30.2234,-97.7697,http://512brewing.com/
1,(512) Brewing Company,(512) Whiskey Barrel Aged Double Pecan Porter,8.2,10.0,Porter,"407 Radam, F200",Austin,Texas,30.2234,-97.7697,http://512brewing.com/
2,(512) Brewing Company,(512) Pale,5.8,10.0,American-Style Pale Ale,"407 Radam, F200",Austin,Texas,30.2234,-97.7697,http://512brewing.com/
3,(512) Brewing Company,(512) IPA,7.0,10.0,American-Style India Pale Ale,"407 Radam, F200",Austin,Texas,30.2234,-97.7697,http://512brewing.com/
4,(512) Brewing Company,(512) Bruin,7.6,10.0,American-Style Brown Ale,"407 Radam, F200",Austin,Texas,30.2234,-97.7697,http://512brewing.com/
5,(512) Brewing Company,(512) ALT,6.0,10.0,German-Style Brown Ale/Altbier,"407 Radam, F200",Austin,Texas,30.2234,-97.7697,http://512brewing.com/
6,(512) Brewing Company,One,8.0,10.0,Belgian-Style Pale Strong Ale,"407 Radam, F200",Austin,Texas,30.2234,-97.7697,http://512brewing.com/
7,(512) Brewing Company,(512) Wit,5.2,10.0,Belgian-Style White,"407 Radam, F200",Austin,Texas,30.2234,-97.7697,http://512brewing.com/
8,21st Amendment Brewery Cafe,Bitter American,3.6,10.0,Special Bitter or Best Bitter,563 Second Street,San Francisco,California,37.7825,-122.3930,http://www.21st-amendment.com/
9,21st Amendment Brewery Cafe,Potrero ESB,5.2,10.0,Special Bitter or Best Bitter,563 Second Street,San Francisco,California,37.7825,-122.3930,http://www.21st-amendment.com/
10,21st Amendment Brewery Cafe,General Pippo's Porter,5.5,10.0,Porter,563 Second Street,San Francisco,California,37.7825,-122.3930,http://www.21st-amendment.com/
11,21st Amendment Brewery Cafe,Amendment Pale Ale,5.2,10.0,American-Style Pale Ale,563 Second Street,San Francisco,California,37.7825,-122.3930,http://www.21st-amendment.com/
12,21st Amendment Brewery Cafe,21A IPA,7.2,10.0,American-Style India Pale Ale,563 Second Street,San Francisco,California,37.7825,-122.3930,http://www.21st-amendment.com/
13,21st Amendment Brewery Cafe,Double Trouble IPA,9.8,10.0,Imperial or Double India Pale Ale,563 Second Street,San Francisco,California,37.7825,-122.3930,http://www.21st-amendment.com/
14,21st Amendment Brewery Cafe,North Star Red,5.8,10.0,American-Style Amber/Red Ale,563 Second Street,San Francisco,California,37.7825,-122.3930,http://www.21st-amendment.com/
15,21st Amendment Brewery Cafe,South Park Blonde,5.0,10.0,Golden or Blonde Ale,563 Second Street,San Francisco,California,37.7825,-122.3930,http://www.21st-amendment.com/
16,21st Amendment Brewery Cafe,Oyster Point Oyster Stout,5.9,10.0,American-Style Stout,563 Second Street,San Francisco,California,37.7825,-122.3930,http://www.21st-amendment.com/
17,21st Amendment Brewery Cafe,563 Stout,5.0,10.0,American-Style Stout,563 Second Street,San Francisco,California,37.7825,-122.3930,http://www.21st-amendment.com/
18,21st Amendment Brewery Cafe,Watermelon Wheat,5.5,10.0,Belgian-Style Fruit Lambic,563 Second Street,San Francisco,California,37.7825,-122.3930,http://www.21st-amendment.com/
19,Aberdeen Brewing,Scottish Ale,4.8,10.0,Undefined-Ignore,210 Aberdeen Dr.,Valparaiso,Indiana,41.4392,-87.1078,NaN
20,Abita Brewing Company,Abbey Ale,4.5,10.0,Classic English-Style Pale Ale,PO Box 1510,Abita Springs,Louisiana,30.5049,-89.9440,http://www.abita.com/
21,Abita Brewing Company,Restoration Pale Ale,5.0,10.0,American-Style Pale Ale,PO Box 1510,Abita Springs,Louisiana,30.5049,-89.9440,http://www.abita.com/
22,Abita Brewing Company,Turbodog,4.5,10.0,Dark American-Belgo-Style Ale,PO Box 1510,Abita Springs,Louisiana,30.5049,-89.9440,http://www.abita.com/
23,Abita Brewing Company,Abita Jockamo IPA,6.5,10.0,American-Style India Pale Ale,PO Box 1510,Abita Springs,Louisiana,30.5049,-89.9440,http://www.abita.com/
24,Abita Brewing Company,Christmas Ale,5.5,38.0,American-Style Brown Ale,PO Box 1510,Abita Springs,Louisiana,30.5049,-89.9440,http://www.abita.com/
25,Abita Brewing Company,Satsuma Harvest Wit,5.1,10.0,Belgian-Style White,PO Box 1510,Abita Springs,Louisiana,30.5049,-89.9440,http://www.abita.com/
26,Abita Brewing Company,S.O.S,4.5,10.0,German-Style Pilsener,PO Box 1510,Abita Springs,Louisiana,30.5049,-89.9440,http://www.abita.com/
27,Abita Brewing Company,Abita Amber,4.5,10.0,Vienna-Style Lager,PO Box 1510,Abita Springs,Louisiana,30.5049,-89.9440,http://www.abita.com/
28,Abita Brewing Company,Wheat,4.5,10.0,Vienna-Style Lager,PO Box 1510,Abita Springs,Louisiana,30.5049,-89.9440,http://www.abita.com/
29,Abita Brewing Company,Fall Fest,4.5,10.0,German-Style Oktoberfest,PO Box 1510,Abita Springs,Louisiana,30.5049,-89.9440,http://www.abita.com/
...,...,...,...,...,...,...,...,...,...,...,...
4454,Zea Rotisserie and Brewery,Z.P.A. India Pale Ale,4.5,10.0,American-Style Pale Ale,1525 St. Charles Avenue,New Orleans,Louisiana,29.9386,-90.0760,http://www.zearestaurants.com
4455,Zea Rotisserie and Brewery,Category 5 Strong Ale,4.5,10.0,American-Style Pale Ale,1525 St. Charles Avenue,New Orleans,Louisiana,29.9386,-90.0760,http://www.zearestaurants.com
4456,Zea Rotisserie and Brewery,Lager,4.5,10.0,American-Style Lager,1525 St. Charles Avenue,New Orleans,Louisiana,29.9386,-90.0760,http://www.zearestaurants.com
4457,Yegua Creek Brewing - Dallas,Cask Scotch Ale,4.5,10.0,Undefined-Ignore,2920 North Henderson Ave,Dallas,Texas,32.8210,-96.7848,NaN
4458,Yegua Creek Brewing - Dallas,Icehaus Pale Ale,4.5,10.0,American-Style Pale Ale,2920 North Henderson Ave,Dallas,Texas,32.8210,-96.7848,NaN
4459,Yegua Creek Brewing - Dallas,White Rock Red,4.5,10.0,American-Style Amber/Red Ale,2920 North Henderson Ave,Dallas,Texas,32.8210,-96.7848,NaN
4460,Yegua Creek Brewing - Dallas,Oktoberfest,4.5,10.0,German-Style Oktoberfest,2920 North Henderson Ave,Dallas,Texas,32.8210,-96.7848,NaN
4461,Yegua Creek Brewing - Dallas,Golden Wheat,4.5,10.0,American-Style Lager,2920 North Henderson Ave,Dallas,Texas,32.8210,-96.7848,NaN
4462,Yegua Creek Brewing - Dallas,Blueberry Blonde,4.5,10.0,Light American Wheat Ale or Lager,2920 North Henderson Ave,Dallas,Texas,32.8210,-96.7848,NaN
4463,Yuengling & Son Brewing,Yuengling Black and Tan,4.7,10.0,Undefined-Ignore,310 Mill Creek Avenue,Pottsville,Pennsylvania,40.7000,-76.1747,http://www.yuengling.com
4464,Yuengling & Son Brewing,Yuengling Porter,4.7,10.0,Porter,310 Mill Creek Avenue,Pottsville,Pennsylvania,40.7000,-76.1747,http://www.yuengling.com
4465,Yuengling & Son Brewing,Lord Chesterfield Ale,5.4,10.0,American-Style Pale Ale,310 Mill Creek Avenue,Pottsville,Pennsylvania,40.7000,-76.1747,http://www.yuengling.com
4466,Yuengling & Son Brewing,Yuengling Bock Beer,4.5,10.0,Traditional German-Style Bock,310 Mill Creek Avenue,Pottsville,Pennsylvania,40.7000,-76.1747,http://www.yuengling.com
4467,Yuengling & Son Brewing,Yuengling Lager,4.4,10.0,American-Style Lager,310 Mill Creek Avenue,Pottsville,Pennsylvania,40.7000,-76.1747,http://www.yuengling.com
4468,Yuengling & Son Brewing,Yuengling Premium Beer,4.4,10.0,American-Style Lager,310 Mill Creek Avenue,Pottsville,Pennsylvania,40.7000,-76.1747,http://www.yuengling.com
4469,Yuengling & Son Brewing,Yuengling Lager Light,3.4,10.0,American-Style Light Lager,310 Mill Creek Avenue,Pottsville,Pennsylvania,40.7000,-76.1747,http://www.yuengling.com
4470,Yuengling & Son Brewing,Yuengling Premium Light,3.5,10.0,American-Style Light Lager,310 Mill Creek Avenue,Pottsville,Pennsylvania,40.7000,-76.1747,http://www.yuengling.com
4471,Yellowstone Valley Brewing,Grizzly Wulff Wheat,5.3,10.0,Undefined-Ignore,2123 1st Avenue North,Billings,Montana,45.7861,-108.4980,http://www.yellowstonevalleybrew.com
4472,Yazoo Brewing,ESB,4.5,10.0,Extra Special Bitter,910 Division St,Nashville,Tennessee,36.1510,-86.7821,http://www.yazoobrew.com
4473,Yazoo Brewing,Sly Rye Porter,5.7,10.0,Porter,910 Division St,Nashville,Tennessee,36.1510,-86.7821,http://www.yazoobrew.com
4474,Yazoo Brewing,Pale Ale,5.8,10.0,American-Style Pale Ale,910 Division St,Nashville,Tennessee,36.1510,-86.7821,http://www.yazoobrew.com
4475,Yazoo Brewing,Dos Perros,3.5,10.0,Dark American-Belgo-Style Ale,910 Division St,Nashville,Tennessee,36.1510,-86.7821,http://www.yazoobrew.com
4476,Yazoo Brewing,Pale Ale,5.8,55.0,American-Style Strong Pale Ale,910 Division St,Nashville,Tennessee,36.1510,-86.7821,http://www.yazoobrew.com
4477,Yazoo Brewing,Dos Perros,3.5,21.0,American-Style Brown Ale,910 Division St,Nashville,Tennessee,36.1510,-86.7821,http://www.yazoobrew.com
4478,Yazoo Brewing,Onward Stout,3.8,10.0,American-Style Stout,910 Division St,Nashville,Tennessee,36.1510,-86.7821,http://www.yazoobrew.com
4479,Yazoo Brewing,Onward Stout,3.8,35.0,American-Style Stout,910 Division St,Nashville,Tennessee,36.1510,-86.7821,http://www.yazoobrew.com
4480,Yazoo Brewing,Hefeweizen,5.0,10.0,South German-Style Hefeweizen,910 Division St,Nashville,Tennessee,36.1510,-86.7821,http://www.yazoobrew.com
4481,Yazoo Brewing,Hefeweizen,5.0,13.0,South German-Style Hefeweizen,910 Division St,Nashville,Tennessee,36.1510,-86.7821,http://www.yazoobrew.com
4482,Aviator Brewing Company,HotRod Red,6.1,10.0,Irish-Style Red Ale,209 Technology Park Lane,Fuquay Varina,North Carolina,35.6197,-78.8085,http://www.aviatorbrew.com/
4483,Aviator Brewing Company,Old BullDog Extra Special,5.8,10.0,American-Style Strong Pale Ale,209 Technology Park Lane,Fuquay Varina,North Carolina,35.6197,-78.8085,http://www.aviatorbrew.com/

In [14]:
beerdf.dtypes

brewery_name     object
beer_name        object
abv             float64
ibu             float64
style_name       object
address1         object
city             object
state            object
latitude        float64
longitude       float64
website          object
dtype: object

In [15]:
beerdf = beerdf.rename(columns={'brewery_name': 'brewery','beer_name':'beer','style_name':'style','address1':'address'})
beerdf.columns.values

array(['brewery', 'beer', 'abv', 'ibu', 'style', 'address', 'city',
       'state', 'latitude', 'longitude', 'website'], dtype=object)

In [17]:
beerdf.to_csv('breweries_final.csv', index=False)